import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from 'bun:test'

const rootDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

const readRepositoryFile = (fileName) => readFile(path.resolve(rootDirectory, fileName), 'utf8')

test('release preflight runs the fast checks before the build', async () => {
  const releaseConfig = JSON.parse(await readRepositoryFile('.release-it.json'))

  expect(releaseConfig.hooks['before:init']).toEqual(['bun run check:fast', 'bun run build'])
})

test('generated release output has an explicit Prettier policy', async () => {
  const prettierIgnore = await readRepositoryFile('.prettierignore')
  const prettierIgnoreLines = prettierIgnore.trim().split('\n')
  const releaseFileIndex = prettierIgnoreLines.indexOf('RELEASE.MD')

  expect(releaseFileIndex).toBeGreaterThan(0)
  expect(prettierIgnoreLines[releaseFileIndex - 1]).toContain('generated by Geeto CLI')
})
